version: "3"

services:
  app:
    image: vecser/devops-for-programmers-project-lvl1
    build:
      context: .
      dockerfile: Dockerfile.production
    command: bash -c 'sleep 3 && npm test'
    volumes:
      - ./app/.env.example:/app/.env
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:14.5
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
