version: "3"

services:
  app:
    image: vecser/devops-for-programmers-project-lvl1
    build:
      context: .
      dockerfile: Dockerfile.production
    command: bash -c 'sleep 3 && npm test'
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: $DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
    depends_on:
      - db

  db:
    image: postgres:14.5
    environment:
      POSTGRES_NAME: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PORT: ${DATABASE_PORT}
      POSTGRES_HOST: ${DATABASE_HOST}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
