name: push

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare Env
        run: make prepare-env

      - name: Run tests
        run: make ci

  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: vecser/devops-for-programmers-project-lvl1:latest
          file: "./Dockerfile.production"
    needs: test
